apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnpl-catalog-service
  labels:
    app: bnpl-catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bnpl-catalog-service
  template:
    metadata:
      labels:
        app: bnpl-catalog-service
    spec:
      containers:
        - name: bnpl-catalog-service
          image: bnpl-catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://bnpl-config-service
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://bnpl-postgres/bnpldb_catalog
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
