apiVersion: apps/v1
kind: Deployment
metadata:
  name: bnpl-catalog-service
  labels:
    app: bnpl-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bnpl-catalog-service
  template:
    metadata:
      labels:
        app: bnpl-catalog-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9001"
    spec:
      containers:
        - name: bnpl-catalog-service
          image: bnpl-catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_PROFILES_ACTIVE
              value: testdata
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            initialDelaySeconds: 50
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
            initialDelaySeconds: 45
            periodSeconds: 15
          volumeMounts:
            - name: bnpl-catalog-config-volume
              mountPath: /workspace/config
      volumes:
        - name: bnpl-catalog-config-volume
          configMap:
            name: bnpl-catalog-config

